services:
  - type: web
    name: argos-backend
    env: node
    region: oregon
    plan: free
    buildCommand: cd nodejs_space && yarn install && yarn build && yarn prisma generate
    startCommand: cd nodejs_space && yarn start:prod
    envVars:
      - key: NODE_VERSION
        value: 18.18.0
      - key: DATABASE_URL
        sync: false
      - key: ABACUSAI_API_KEY
        sync: false
