services:
  - type: web
    name: argos-backend
    env: node
    region: oregon
    plan: free
    rootDir: nodejs_space
    buildCommand: yarn install && yarn prisma generate && yarn prisma migrate deploy && yarn build
    startCommand: yarn start:prod
    envVars:
      - key: NODE_VERSION
        value: 18.18.0
      - key: DATABASE_URL
        sync: false
      - key: ABACUSAI_API_KEY
        sync: false
      - key: AUTOREMOTE_USER_KEY
        sync: false
      - key: AUTOREMOTE_BASE_URL
        sync: false
